# Use official Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy files
COPY Requirements.txt .
COPY app.py .
COPY model.pkl .

# Install dependencies
RUN pip install --no-cache-dir -r Requirements.txt

# Expose port
EXPOSE 5000

# Start Flask app
CMD ["python", "app.py"]